# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'PayWingsOnboardingKYC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayWingsOnboardingKYC

  pod 'VideoID', '7.1.31'
  pod 'IdensicMobileSDK', :http => 'https://github.com/PayWings/PayWingsOnboardingKycSDK-iOS-IdensicMobile/archive/v2.1.0.tar.gz'



  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
  end

end
